'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';

interface Blueprint {
  id: string;
  title: string;
  idea: string;
  content: string | null;
  status: string;
  createdAt: string;
}

interface BlueprintViewProps {
  blueprint: Blueprint;
}

export default function BlueprintView({ blueprint }: BlueprintViewProps) {
  const [expanded, setExpanded] = useState(false);

  const preview = blueprint.content 
    ? blueprint.content.slice(0, 500) + (blueprint.content.length > 500 ? '...' : '')
    : 'Your blueprint is being generated by the THINKOVR Engine...';

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="relative overflow-hidden rounded-xl"
      style={{
        background: 'linear-gradient(145deg, #0a1628 0%, #1e3a5f 50%, #0a1628 100%)',
        border: '2px solid rgba(59, 130, 246, 0.4)',
        boxShadow: '0 8px 32px rgba(59, 130, 246, 0.3), inset 0 1px 0 rgba(255,255,255,0.1)',
      }}
    >
      {/* Blueprint Header */}
      <div className="relative px-6 py-5 border-b border-blue-500/30">
        <div className="flex items-center gap-4">
          <div className="w-14 h-14 rounded-xl bg-blue-500/20 flex items-center justify-center">
            <svg className="w-8 h-8 text-blue-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <div className="flex-1">
            <h2 className="text-xl font-bold text-blue-100 tracking-wide">BLUEPRINT</h2>
            <p className="text-sm text-blue-300/70">Foundation Strategy Document</p>
          </div>
          <div className="px-4 py-1.5 rounded-full bg-blue-500/20 border border-blue-500/30 text-blue-300 text-xs font-semibold tracking-wider">
            THINKOVR
          </div>
        </div>
      </div>

      {/* Blueprint Content */}
      <div className="p-6">
        <h3 className="text-lg font-semibold text-blue-200 mb-3">{blueprint.title}</h3>
        
        <div className="mb-4 p-4 rounded-lg bg-blue-900/20 border border-blue-500/20">
          <p className="text-sm text-blue-200/80 italic">
            &ldquo;{blueprint.idea}&rdquo;
          </p>
        </div>

        <div className="prose prose-invert prose-blue max-w-none">
          <div className="text-slate-300 leading-relaxed whitespace-pre-wrap">
            {expanded ? blueprint.content : preview}
          </div>
        </div>

        {blueprint.content && blueprint.content.length > 500 && (
          <button
            onClick={() => setExpanded(!expanded)}
            className="mt-4 text-sm text-blue-400 hover:text-blue-300 transition-colors flex items-center gap-2"
          >
            {expanded ? 'Show Less' : 'Read Full Blueprint'}
            <svg className={`w-4 h-4 transition-transform ${expanded ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </button>
        )}
      </div>

      {/* Blueprint Footer */}
      <div className="px-6 py-4 border-t border-blue-500/30 bg-blue-900/20">
        <div className="flex items-center justify-between text-xs text-blue-400/60">
          <span className="tracking-wider">CLASSIFICATION: STANDARD</span>
          <span>ID: {blueprint.id.slice(0, 8).toUpperCase()}</span>
        </div>
      </div>
    </motion.div>
  );
}
