export default function DisclaimerPage() {
  return (
    <div className="bespoke-root" style={{ padding: '120px 0 80px' }}>
      <div className="bespoke-container" style={{ maxWidth: 800 }}>
        <div style={{ textAlign: 'center', marginBottom: 48 }}>
          <p style={{ fontFamily: 'var(--font-mono)', fontSize: '0.55rem', letterSpacing: '0.3em', color: '#C9A84C', textTransform: 'uppercase', marginBottom: 16 }}>Legal</p>
          <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(1.6rem, 4vw, 2.5rem)', fontWeight: 700, letterSpacing: '0.05em', textTransform: 'uppercase', color: '#F0EAD6', lineHeight: 1.1, marginBottom: 16 }}>
            Complete Disclaimer, Assumption of Risk, and Terms of Use
          </h1>
          <div style={{ width: 60, height: 1, background: 'var(--gold)', margin: '0 auto' }} />
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 40 }}>
          <section>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '0.95rem', letterSpacing: '0.12em', textTransform: 'uppercase', color: '#C9A84C', marginBottom: 16 }}>1. Absolute Limitation of Liability</h2>
            <p style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8, marginBottom: 12 }}>
              The use of Thinkovr and its AI-generated content is entirely at your own risk. Under no circumstances, legal theory, or jurisdiction shall the website, its owners, administrators, developers, affiliates, or partners be held accountable, responsible, or liable for anything. This includes, but is not limited to:
            </p>
            <ul style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8, paddingLeft: 20, listStyle: 'disc' }}>
              <li style={{ marginBottom: 6 }}>Direct, indirect, incidental, or catastrophic damages.</li>
              <li style={{ marginBottom: 6 }}>Financial loss, career setbacks, or loss of income.</li>
              <li style={{ marginBottom: 6 }}>Emotional, psychological, or physical distress.</li>
              <li style={{ marginBottom: 6 }}>Any life decisions made based on the AI&apos;s output.</li>
            </ul>
            <p style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8, fontStyle: 'italic' }}>
              The service is provided strictly &ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE&rdquo; with zero warranties, express or implied.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '0.95rem', letterSpacing: '0.12em', textTransform: 'uppercase', color: '#C9A84C', marginBottom: 16 }}>2. Intellectual Property and Idea Assignment</h2>
            <p style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8, marginBottom: 12 }}>
              By utilizing this platform, you expressly waive all rights to any intellectual property you submit or generate. You agree that:
            </p>
            <ul style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8, paddingLeft: 20, listStyle: 'disc' }}>
              <li style={{ marginBottom: 8 }}><strong style={{ color: '#F0EAD6' }}>Total Ownership:</strong> Thinkovr automatically claims full, exclusive, irrevocable, and perpetual rights to any blueprint provided, any idea submitted, and any word prompted into the system.</li>
              <li style={{ marginBottom: 8 }}><strong style={{ color: '#F0EAD6' }}>Unrestricted Use:</strong> The company retains the absolute right to claim, publish, monetize, sell, modify, or discard any concept, blueprint, or text generated through this platform.</li>
              <li style={{ marginBottom: 8 }}><strong style={{ color: '#F0EAD6' }}>Approval Status Irrelevant:</strong> This transfer of ownership applies fully whether you, the user, approve or disapprove of the generated output. You are relinquishing all claims to the ideas you input and the blueprints you receive.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '0.95rem', letterSpacing: '0.12em', textTransform: 'uppercase', color: '#C9A84C', marginBottom: 16 }}>3. No Professional Advice Guarantee</h2>
            <p style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8, marginBottom: 12 }}>
              The blueprints and roadmaps generated by this AI do not represent professional counsel.
            </p>
            <ul style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8, paddingLeft: 20, listStyle: 'disc' }}>
              <li style={{ marginBottom: 8 }}><strong style={{ color: '#F0EAD6' }}>Not Experts:</strong> The AI, owners, administrators, and developers are not licensed financial advisors, career counselors, legal experts, therapists, or medical professionals.</li>
              <li style={{ marginBottom: 8 }}><strong style={{ color: '#F0EAD6' }}>AI Hallucinations:</strong> Generative AI is prone to errors, logical fallacies, and fabrications (&ldquo;hallucinations&rdquo;). You are solely responsible for independently verifying every claim, step, and suggestion before taking any real-world action.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '0.95rem', letterSpacing: '0.12em', textTransform: 'uppercase', color: '#C9A84C', marginBottom: 16 }}>4. Indemnification</h2>
            <p style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8 }}>
              You agree to indemnify, defend, and hold harmless Thinkovr, its developers, administrators, and owners from any and all claims, liabilities, expenses, and damages—including legal fees—arising from your use of the website, your reliance on its generated blueprints, or your violation of these terms.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '0.95rem', letterSpacing: '0.12em', textTransform: 'uppercase', color: '#C9A84C', marginBottom: 16 }}>5. Proprietary Technology and Trade Secrets</h2>
            <p style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8, marginBottom: 12 }}>
              The specific methodologies, algorithms, prompt chains, backend integrations, and artificial intelligence models utilized by Thinkovr to generate blueprints are the exclusive trade secrets and proprietary information of the company.
            </p>
            <ul style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8, paddingLeft: 20, listStyle: 'disc' }}>
              <li style={{ marginBottom: 8 }}><strong style={{ color: '#F0EAD6' }}>No Obligation to Disclose:</strong> We are under no obligation to reveal, explain, or document how the AI processes inputs or generates outputs.</li>
              <li style={{ marginBottom: 8 }}><strong style={{ color: '#F0EAD6' }}>Black Box Operation:</strong> You acknowledge that the service operates as a proprietary &ldquo;black box.&rdquo; We reserve the absolute right to modify, obscure, or keep our technological approach entirely secret at our sole discretion.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '0.95rem', letterSpacing: '0.12em', textTransform: 'uppercase', color: '#C9A84C', marginBottom: 16 }}>6. User Data Privacy and Law Enforcement Disclosure</h2>
            <p style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8, marginBottom: 12 }}>
              While Thinkovr claims total intellectual property rights over the content of your prompts and blueprints (as outlined in Section 2), we handle your Personally Identifiable Information (PII)—such as your name, email address, or billing details—separately.
            </p>
            <ul style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8, paddingLeft: 20, listStyle: 'disc' }}>
              <li style={{ marginBottom: 8 }}><strong style={{ color: '#F0EAD6' }}>General Privacy:</strong> Your PII will not be sold, rented, or shared with third-party advertisers or external corporations for marketing purposes.</li>
              <li style={{ marginBottom: 8 }}><strong style={{ color: '#F0EAD6' }}>Exceptions for Authorities:</strong> We reserve the absolute right, and will fully comply with any legal obligation, to disclose your PII, user history, prompts, blueprints, and connection data to local, provincial, or federal/national law enforcement agencies, regulatory bodies, or courts.</li>
              <li style={{ marginBottom: 8 }}><strong style={{ color: '#F0EAD6' }}>Cooperation Trigger:</strong> Such disclosure will occur if we receive a valid subpoena, warrant, or court order, or if the owners, administrators, or developers suspect the platform is being used to plan illegal, harmful, or legally questionable activities.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '0.95rem', letterSpacing: '0.12em', textTransform: 'uppercase', color: '#C9A84C', marginBottom: 16 }}>7. Acceptable Use and Prohibited Conduct</h2>
            <p style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8 }}>
              You agree not to use Thinkovr to generate blueprints for any illegal, unethical, or harmful purposes. This includes, but is not limited to, planning criminal enterprises, financial fraud, physical harm to self or others, or creating malicious software. The company assumes no liability for the generation of such blueprints, and any such attempts will result in immediate data handover to relevant authorities.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '0.95rem', letterSpacing: '0.12em', textTransform: 'uppercase', color: '#C9A84C', marginBottom: 16 }}>8. Termination of Service and Account Banning</h2>
            <p style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8 }}>
              The owners, administrators, and developers of Thinkovr reserve the right to terminate your access, ban your IP address, or delete your account at any time, without prior notice or explanation, for any reason or no reason at all.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '0.95rem', letterSpacing: '0.12em', textTransform: 'uppercase', color: '#C9A84C', marginBottom: 16 }}>9. Age Restriction</h2>
            <p style={{ fontFamily: 'var(--font-body)', fontSize: '0.92rem', color: '#BDB49A', lineHeight: 1.8 }}>
              You must be at least 18 years of age (or the age of legal majority in your jurisdiction) to use this platform. By submitting a prompt, you warrant that you meet this age requirement. If you are under the required age, you are strictly prohibited from using this service.
            </p>
          </section>
        </div>

        <div style={{ marginTop: 60, borderTop: '1px solid rgba(201,168,76,0.12)', paddingTop: 32, textAlign: 'center' }}>
          <a href="/" style={{ fontFamily: 'var(--font-mono)', fontSize: '0.6rem', letterSpacing: '0.15em', color: '#C9A84C', textTransform: 'uppercase', textDecoration: 'none' }}>
            ← Back to Home
          </a>
        </div>
      </div>
    </div>
  );
}
